# Generated by Django 4.2.1 on 2023-06-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_bloguser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogName', models.CharField(max_length=200)),
                ('Image', models.ImageField(default='', upload_to='pics')),
                ('Description', models.TextField()),
            ],
        ),
    ]
