# Generated by Django 4.2.1 on 2023-08-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogName', models.CharField(max_length=200)),
                ('Description', models.TextField()),
            ],
        ),
    ]
