# Generated by Django 4.2.1 on 2023-08-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_blogdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Resumedoc', models.FileField(upload_to='media')),
                ('Mobileno', models.IntegerField()),
            ],
        ),
    ]
