# Generated by Django 4.2.1 on 2023-08-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Mobileno',
            field=models.CharField(max_length=32),
        ),
    ]
