# Generated by Django 4.2.1 on 2023-08-09 14:44

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_student_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updatedate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
